### ISSUE TITLE
Require navigation-prop from one to many

### ISSUE THREAD

**Issue by danmusk** [JonPSmith/EfCore.SoftDeleteServices#1]
Thank you for this library.

I have a question regarding the configuration of the entities involved in a SoftDelete scenario.

In a One-To-Many relationship, Client-ApplicationUser, the Client has a navigation-property CreatedByUser. 
- If I have a ICollection<Client> on the ApplicationUser entity the soft delete works as expected. 
- If I do not have the explicit ICollection<Client> on the ApplicatonUser entity, the softDelete fails with the error: `You cannot soft delete a one-to-one relationship. It causes problems if you try to create a new version.`.

I've created a small demo project for this scenario: https://github.com/danmusk/SoftDeleteServiceTest (https://github.com/danmusk/SoftDeleteServiceTest/blob/master/SoftDeleteOneToOne/Models/ApplicationUser.cs)
In this project I use the LocalDb-SQLServer.

Is it required to explicit define navigationProps on the One-side back to the Many-side?

**Comment by JonPSmith** [comment]
I'm surprised, but it seems that EF Core has assumes its a one-to-one relationships. EF Core has to decide what type of relationship you have if you don't have a navigational property on both ends. You can tell EF Core what the relationship using Fluent API methods like `...HasOne(x => x.CreatedByUser).WiithMany()`.

I hope that fixes it for you

**Comment by danmusk** [comment]
It seems that it does not work to only configure the `Client` side. I managed to get it to work by explicitly add the collection-navigation on the `ApplicationUser` back to `Clients` in the demo-project. In the real project this also works, but it leads to a lot of of extra code, and extra navigation-collections on the User-entity. Also all other One-To-Many seems to need the explicit prop on the "one-side" back to the "many". On the Client table alone it's 3 one-to-many back to the User (CreatedBy, ModifiedBy and DeletedBy) and multiple other relations. So the User-Entity will pretty fast have a lot of (unused) navigational properties. I will keep investigating and test this a bit more, as I really want to use this library to enable SoftDelete in the project.

**Comment by JonPSmith** [comment]
Hmm. This seems a bit strange. Let me know what you find out - I'm interested hear what the problem is.

**Comment by JonPSmith** [comment]
Hi @danmusk,

The relationship you defined is a one-to-many, but without the collection. I have updated the code to detect this and not throw an exception. See version 1.1.3 on NuGet.

Thanks for the pull requests - I didn't use them because I wanted to define specific unit tests, but they were useful to see how you were defining your relationship.

**Comment by danmusk** [comment]
Updated to version 1.1.3 of the nuget in our project, removed the `ICollection<>`'s  we don't need, and everything now work as expected. Thanks for the quick response and fix.
