### ISSUE TITLE
Should i write filters?

### ISSUE THREAD

**Issue by ksydex** [JonPSmith/EfCore.SoftDeleteServices#10]
Hi, is it required to write filters (manually either automatically) to make data hidden from the requests? Or is it automatically done when injecting service in DI? A little bit unclear after reading the wiki.
Thanks!

**Comment by JonPSmith** [comment]
Hi @ksydex,

Yes you do. Have a look at the [General Overview](https://github.com/JonPSmith/EfCore.SoftDeleteServices/wiki/General-Overview) page in the Wiki which talks about your DbContext, or the [Setting up Query Filters to your entities](https://www.thereformedprogrammer.net/introducing-the-efcore-softdeleteservices-library-to-automate-soft-deletes/#2-setting-up-query-filters-to-your-entities) section in the article "Introducing the EfCore.SoftDeleteServices library to automate soft deletes"

**Comment by ksydex** [comment]
> Hi @ksydex,
> 
> Yes you do. Have a look at the [General Overview](https://github.com/JonPSmith/EfCore.SoftDeleteServices/wiki/General-Overview) page in the Wiki which talks about your DbContext, or the [Setting up Query Filters to your entities](https://www.thereformedprogrammer.net/introducing-the-efcore-softdeleteservices-library-to-automate-soft-deletes/#2-setting-up-query-filters-to-your-entities) section in the article "Introducing the EfCore.SoftDeleteServices library to automate soft deletes"

Thanks!
