### ISSUE TITLE
Delete not cascading as expected when some navigation properties are null

### ISSUE THREAD

**Issue by lena-osterhus** [JonPSmith/EfCore.SoftDeleteServices#11]
Thank you for a very useful library!

I think there is a bug in the CascadeWalker on line 77 and 98 - should it perhaps be `continue` instead of `return` when there is no relationship? This way the other navigations are cascaded/walked through, even though one of the navigation values are `null`.

The `principalNavs` are returned in alphabetical order, and if the entity you're soft deleting (cascading) has a `null` value in some navigation property alphabetically prior to another that is in use (and should be soft deleted), the walker will prematurely be returned and the related entity with a value will not be soft deleted.

**Comment by JonPSmith** [comment]
Hi @lena-osterhus,

That sounds bad and I 'll have a look at it.

I assume you found it when using the library in an application and it didn't delete one of the relationships - correct? It would be useful if you add the entity classes that are linked together that failed. If it too complex or confidential, then simplified version of the classes would be useful.

**Comment by lena-osterhus** [comment]
That is correct. Here are simplified versions of the classes:
```
public class Company : ICascadeSoftDelete
{
    public Company(string name)
    {
        Name = name;
    }
    public int Id { get; set; }
    public string Name { get; set; }
    public ICollection<Address>? Addresses { get; set; }
    public ICollection<ExternalId>? ExternalIds { get; set; }
    public byte SoftDeleteLevel { get; set; }
}
```
```
public class Address : ICascadeSoftDelete
{
    public int Id { get; set; }
    public string? Street { get; init; }
    public string? City { get; init; }
    public int? CompanyId { get; set; }
    public Company? Company { get; init; }
    public byte SoftDeleteLevel { get; set; }
}
```
```
public class ExternalId : ICascadeSoftDelete
{
    public ExternalId(string context, string value)
    {
        Context = context;
        Value = value;
    }
    public int Id { get; set; }
    public string Context { get; init; } // The system the value relates to
    public string Value { get; set; }
    public int? CompanyId { get; set; }
    public Company? Company { get; init; }
    public byte SoftDeleteLevel { get; set; }
}
```
OnModelCreating contains this configuration:
```
        modelBuilder.Entity<Address>()
            .HasOne(a => a.Company)
            .WithMany(c => c.Addresses)
            .HasForeignKey(a => a.CompanyId)
            .OnDelete(DeleteBehavior.ClientCascade)
            .HasConstraintName("FK_Addresses_Companies");

        modelBuilder.Entity<ExternalId>()
            .HasOne(e => e.Company)
            .WithMany(c => c.ExternalIds)
            .HasForeignKey(e => e.CompanyId)
            .OnDelete(DeleteBehavior.ClientCascade)
            .HasConstraintName("FK_ExternalId_Company");
```

In my case I wrote a test where I add a `Company` to the database with no `Address` and one `ExternalId`, and then try to cascade soft delete the `Company`. I expected both `Company` and the `ExternalId` to be soft deleted, but only the `Company` was.

**Comment by JonPSmith** [comment]
Hi @lena-osterhus,

Sorry for the delay on looking at this but I was working on something. Anyway I have created a [test](https://github.com/JonPSmith/EfCore.SoftDeleteServices/blob/master/Test/UnitTests/IssuesTests/TestIssue011.cs) and it worked correctly, i.e. the cascade delete set the `Company.SoftDeleteLevel` to 1 and the `ExternalId.SoftDeleteLevel` to 2.

I did look at line 77 and 98 which suggested be changed, but they are looking for further navigational entities from the current entity.

**Comment by lena-osterhus** [comment]
Thank you for taking a look, @JonPSmith!
You are of course right, it works correctly with the classes I supplied you with. It seems I lost the essence of the problem in the simplification. I see now that the problem does not present when the first navigation is a collection. If, however, it is a "NavigationSingleton" the `CascadeWalker` will return without walking to the next navigation.

Could you please try your test with the following changes to the Company class:
```
        public class Company : ICascadeSoftDelete
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public Address? Address { get; set; }
            public ICollection<ExternalId>? ExternalIds { get; set; }
            public byte SoftDeleteLevel { get; set; }
        }
```
And OnModelCreating:
```
            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<Address>()
                    .HasOne(c => c.Company)
                    .WithOne(p => p.Address)
                    .HasForeignKey<Address>(a => a.CompanyId)
                    .OnDelete(DeleteBehavior.ClientCascade)
                    .HasConstraintName("FK_Addresses_Companies");

                modelBuilder.Entity<ExternalId>()
                    .HasOne(e => e.Company)
                    .WithMany(c => c.ExternalIds)
                    .HasForeignKey(e => e.CompanyId)
                    .OnDelete(DeleteBehavior.ClientCascade)
                    .HasConstraintName("FK_ExternalId_Company");
            }
```

**Comment by JonPSmith** [comment]
Ah, that makes more sense. I will have a look at that.

**Comment by JonPSmith** [comment]
Version 2.0.1 contains a fix for the cascade soft delete problem reported in this issue. 

Thanks @lena-osterhus for reporting this.
