### ISSUE TITLE
Add instructions to README

### ISSUE THREAD

**Issue by VictorioBerra** [JonPSmith/EfCore.SoftDeleteServices#15]
Hello and thanks for the useful library!

I notice that the README directs us to the blog posts, which are quite lengthy (but informative).

I think I would help a lot of people to have sections of the README as follows:

## Usage

And then we could details some quick getting-started information so people can drop in this library and start coding rather than having to deep-dive into the blogs to figure it out.

Thoughts?

**Comment by JonPSmith** [comment]
I think you missed the "Documentation can be found in the [Repo's Wiki](https://github.com/JonPSmith/EfCore.SoftDeleteServices/wiki)." in the README file. I believe that what you are looking for.
