### ISSUE TITLE
Configurable lifetime for services

### ISSUE THREAD

**Issue by garyng** [JonPSmith/EfCore.SoftDeleteServices#3]
Thanks for this library!

I am injecting `CascadeSoftDelService` into a `Scoped` service, but `CascadeSoftDelService` (and `SingleSoftDeleteService`) is registered as `Transient` in https://github.com/JonPSmith/EfCore.SoftDeleteServices/blob/4378e1e36e2a9d6e8b154ae4a89e90f6ed5db75c/SoftDeleteServices/Configuration/DiRegisterHelpers.cs#L55-L72

Is it possible to add an optional parameter to `RegisterSoftDelServicesAndYourConfigurations` so that we can change the lifetime of those services?

Thanks!

**Comment by garyng** [comment]
Sorry this issue is from my end and not related to the lifetime of the services.

**Comment by JonPSmith** [comment]
Hi @garyng. No problem. Glad you found the problem.
