### ISSUE TITLE
Some Examples in read me would be good

### ISSUE THREAD

**Issue by davidbuckleyni** [JonPSmith/EfCore.SoftDeleteServices#4]
As with every gitthub people love examples show usage and setup and a simple implementation that would be used instead of having to go into source to see if its fit for purpose

**Comment by JonPSmith** [comment]
Hi @davidbuckleyni,

You might find the article [Introducing the EfCore.SoftDeleteServices library to automate soft deletes]( https://www.thereformedprogrammer.net/introducing-the-efcore-softdeleteservices-library-to-automate-soft-deletes/), which is listed in the About section of this repo.

Also, the [EfCore.SoftDeleteServices Wiki](https://github.com/JonPSmith/EfCore.SoftDeleteServices/wiki) has more information (link to this can be found in the readme file.

I hope that helps.
